[tools]
go = "1.27.1"
lefthook = "2.1.10"
node = "25.9.0"
"npm:@antfu/ni" = "30.3.0"
"npm:pnpm" = "11.17.0"
"npm:turbo" = "2.10.12"
"pipx:graphifyy" = "0.9.53"
"pipx:serena-agent" = "1.7.0"
rust = "1.95.0"
uv = "0.12.9"

[hooks]
postinstall = "lefthook install"

[env]
MISE_PIN = true
