// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BunRecord = {
  body: string;
  yakubun: string;
  tekisetsu: boolean | null;
  imi: boolean | null;
  bunpo: boolean | null;
  shiteki: string | null;
  hinto: string | null;
};
