// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenbunSummary = {
  id: string;
  firstLine: string;
  gakushuGengo: string;
  createdAt: string;
};
