// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BunRecord } from "./BunRecord";

export type GenbunRecord = {
  id: string;
  body: string;
  gakushuGengo: string;
  createdAt: string;
  buns: Array<BunRecord>;
};
